### ISSUE TITLE
[BUG]  Error occured while attempting to link skeleton

### ISSUE THREAD

**Issue by Kurochi51** [XIV-Tools/CustomizePlus#191]
I think this started after the latest update? I could be wrong tho.
This gets spammed pretty much since I start the game
`[ERR] [CustomizePlus] Error occured while attempting to link skeleton: Armature (#0) on Default with 2 bone/s`
after penumbra loaded from an update it changed to
`[ERR] [CustomizePlus] Error occured while attempting to link skeleton: Armature (#0) on Default with 33 bone/s`

Turning the plugin off and back on doesn't bring the error again. These are the profiles:
![](https://i.imgur.com/05YwJlD.png)

**Comment by StoiaCode** [comment]
So, what doesnt work?

**Comment by Kurochi51** [comment]
That's a good question, I haven't looked around, but right now the log spam kinda results in a big log file.

**Comment by StoiaCode** [comment]
¯\_(ツ)_/¯
Its kind off just Default that causes that log to appear that regular. And since the log just gets deleted on every game restart, I kind of don't see this as a big issue right now. If I get the time, I may investigate it someday, but I wouldn't hold my horses.

**Comment by Kurochi51** [comment]
I mean, fair enough, but it does make the log / log console unusable.

**Comment by StoiaCode** [comment]
Wait, I just checked something and, I dont think we even have DefaultCutscene anymore? Its just all Default now. 
Check if the log calms down when you disable that profile, and if your scales applie in cutscenes as they should. 

if that doesnt work ill just disable this logline for Profiles named Default.

**Comment by StoiaCode** [comment]
So
1. You log in to your character
2. You check log
3. Log is spammed (and scale isnt working) 
4. you disable and enable the Default scale
5. you check log
6. log isnt spammed (and scale is working)
Correct?

**Comment by Kurochi51** [comment]
Yes

**Comment by Kurochi51** [comment]
I now get this spammed when I disable and enable Default scale 🤔 Only thing that changed is dalamud staging getting updated...
> [ERR] [CustomizePlus] Exception while rendering character profiles:
	System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at CustomizePlus.Data.Armature.Armature.ApplyPiecewiseTransformation(GameObject obj) in D:\a\CustomizePlus\CustomizePlus\CustomizePlus\Data\Armature\Armature.cs:line 446
   at CustomizePlus.Data.Armature.ArmatureManager.ApplyArmatureTransforms() in D:\a\CustomizePlus\CustomizePlus\CustomizePlus\Data\Armature\ArmatureManager.cs:line 83
   at CustomizePlus.Data.Armature.ArmatureManager.RenderCharacterProfiles(CharacterProfile[] profiles) in D:\a\CustomizePlus\CustomizePlus\CustomizePlus\Data\Armature\ArmatureManager.cs:line 24
