### ISSUE TITLE
C+ Not working -  "Exception during raise of "Void Draw()""

### ISSUE THREAD

**Issue by Nanu308** [XIV-Tools/CustomizePlus#213]
Hey, 

I have a weird issue with C+ where it does not work at all for me and seems to crash on occasion? 

Here is the attached log, hope it helps out.

```
12:17:33.860 INF | [CustomizePlus] Asserting that Profile 'Sizeeeee' on XXX XXXX is enabled...
12:17:33.860 DBG | [CustomizePlus] Sending local player update message: Sizeeeee - XXX XXXX
12:17:35.027 INF | [CustomizePlus] Creating new copy of Profile 'Sizeeeee' on XXX XXXX for editing...
12:17:35.030 DBG | [CustomizePlus] Rebuilt Armature (#2) on XXX XXXX with 132 bone/s
12:17:35.030 DBG | [CustomizePlus] Instantiated Armature (#2) on XXX XXXX with 132 bone/s, attached to Profile 'Sizeeeee' on XXX XXXX
12:17:35.030 DBG | [CustomizePlus] Added 'Armature (#2) on XXX XXXX with 132 bone/s' to cache
12:19:00.610 INF | [CustomizePlus] Saving changes to Profile 'Sizeeeee' on XXX XXXX to manager...
12:19:00.610 DBG | [CustomizePlus] E:\AppData - SSD\Roaming\XIVLauncher\pluginConfigs\CustomizePlus\XXX XXXX-Sizeeeee-1685873139.profile
12:19:00.610 DBG | [CustomizePlus] E:\AppData - SSD\Roaming\XIVLauncher\pluginConfigs\CustomizePlus\XXX XXXX-Sizeeeee-1685873139.profile
12:19:00.610 DBG | [CustomizePlus] Sending local player update message: Sizeeeee - XXX XXXX
12:19:08.893 DBG | [CustomizePlus] E:\AppData - SSD\Roaming\XIVLauncher\pluginConfigs\CustomizePlus\XXX XXXX-Sizeeeee-1685873139.profile
12:19:08.893 DBG | [CustomizePlus] E:\AppData - SSD\Roaming\XIVLauncher\pluginConfigs\CustomizePlus\XXX XXXX-Sizeeeee-1685873139.profile
12:19:28.986 ERR | Exception during raise of "Void Draw()"
12:19:28.986 ERR | System.NullReferenceException: Object reference not set to an instance of an object.
12:19:28.986 ERR |    at CustomizePlus.UI.Windows.BoneEditWindow.DrawContents() in D:\a\CustomizePlus\CustomizePlus\CustomizePlus\UI\Windows\BoneEditWindow.cs:line 244
12:19:28.986 ERR |    at CustomizePlus.UI.WindowBase.Draw() in D:\a\CustomizePlus\CustomizePlus\CustomizePlus\UI\WindowBase.cs:line 51
12:19:28.986 ERR |    at CustomizePlus.UI.UserInterfaceManager.Draw() in D:\a\CustomizePlus\CustomizePlus\CustomizePlus\UI\UserInterfaceManager.cs:line 33
12:19:28.986 ERR |    at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act) in C:\goatsoft\companysecrets\dalamud\Utility\EventHandlerExtensions.cs:line 112
12:20:16.040 INF | [CustomizePlus] Asserting that Profile 'Sizeeeee' on XXX XXXX is enabled...
12:20:16.040 DBG | [CustomizePlus] Sending local player update message: Sizeeeee - XXX XXXX
```

**Comment by StoiaCode** [comment]
I assume XXX XXXX is censored by you?

**Comment by Nanu308** [comment]
An update to this, apparently the changes synchs fine through mare and are shown to my friends, but i am unable to see any changes myself or any live preview of changes i make. I can also not see changes made by friends in it, as that is not shown on my side.

**Comment by StoiaCode** [comment]
Go into the settings and make sure the enable check box is checked.

**Comment by Nanu308** [comment]
> Go into the settings and make sure the enable check box is checked.

Hi, yes this was checked. Apologies for late response, but real life occurred. It is still bugged to this day.

**Comment by RisaDev** [comment]
You can either try testing branch or wait for 2.0 to release for everyone.
