### ISSUE TITLE
Customize hub blank

### ISSUE THREAD

**Issue by RubRue** [XIV-Tools/CustomizePlus#97]
Was playing for a while, UPS failed and pc crashed. Came back onto to play again. Open customize only to see these two. I cannot access customize and I get the error message. I deleted the plugin from experimental, reinstalled it but the result were the same. Please help.

![rpt1](https://user-images.githubusercontent.com/131800904/234344989-aaed3ece-6cea-410a-98df-9a5dae0ea5bd.PNG)
![rpt2](https://user-images.githubusercontent.com/131800904/234344997-aa4184ca-0195-4be3-b897-63bbe858d052.PNG)

**Comment by RubRue** [comment]
Tried changing the name of the json according to the steps, the interface is still black blank. 
Would you like to see the /xllog?

**Comment by RubRue** [comment]
00:49:26.934 | ERR [CustomizePlus] Unable to load plugin config
Newtonsoft.Json.JsonSerializationException: Unexpected end when deserializing object. Path 'BodyScales[21].Bones.j_ko_a_r.Rotation.X', line 49263, position 104675.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ThrowUnexpectedEndException(JsonReader reader, JsonContract contract, Object currentObject, String message)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at CustomizePlus.Util.ConfigurationManager.GetCurrentConfigurationVersion() in C:\Users\marth\source\repos\CustomizePlus\CustomizePlus\Util\ConfigurationManager.cs:line 106
   at CustomizePlus.Util.ConfigurationManager.ConvertConfigIfNeeded(String path) in C:\Users\marth\source\repos\CustomizePlus\CustomizePlus\Util\ConfigurationManager.cs:line 71
   at CustomizePlus.Util.ConfigurationManager.LoadConfigurationFromFile(String path) in C:\Users\marth\source\repos\CustomizePlus\CustomizePlus\Util\ConfigurationManager.cs:line 42
   at CustomizePlus.Plugin..ctor(DalamudPluginInterface pluginInterface) in C:\Users\marth\source\repos\CustomizePlus\CustomizePlus\Plugin.cs:line 93
00:49:26.945 | ERR [CustomizePlus] Error loading config
System.NullReferenceException: Object reference not set to an instance of an object.
   at CustomizePlus.Plugin.LoadConfig(Boolean autoModeUpdate) in C:\Users\marth\source\repos\CustomizePlus\CustomizePlus\Plugin.cs:line 139
{ } [ Send ]


P.S there were a few more lines but they build up into abt a few pages(?) so i only took the error

**Comment by StoiaCode** [comment]
If you are technically inclined you can run your CustomizePlus.json through a linter and repair it yourself. Else drop it in here and I'll try my luck when I get time. Potentially your scales are just gone tho.

**Comment by RubRue** [comment]
[FullList.docx](https://github.com/XIV-Tools/CustomizePlus/files/11325490/FullList.docx)
I'm not too sure what you meant by repair though a linter, sorry. 
I can make scales again ahahah, not having the plugin is worse.
Thank you for your time!

**Comment by StoiaCode** [comment]
In the file path you just renamed the other file in, there is another file called CustomizePlus, drop that file in here and delete it from where it currently is. Then it should work again tho all scales are gone.

**Comment by RubRue** [comment]
Excuse me for my cluelessness, when you say "In the file path you just renamed the other file in" did you meant change 'CustomizePlus_OLD.json' back to 'CustomizePlus_v0.json'? 
Sorry I don't know how to share in other format so i used google drive.
https://drive.google.com/file/d/1W7AbYFUay4gDkdFLkDh_A-VUy7xQzf2j/view?usp=sharing

ill let you know if it works or not
